---
title: Basic Description of Models
format:
    pdf:
        toc: false
---

# Background

Data are collected from FlowCam images of microplankton from the Mission-Aransas Estuary. Samples range from 2014 to 2021 collected roughly every month at four stations. Images were initially segemented using FlowCam's VisualSpreadsheet (version ranged from 2.0 to 4.0) which provided collages of individual vignettes of particles. Single image files were then extracted using MorphoCut \[will need to cite and link code\], which formats images to be individually processed in EcoTaxa. The vignettes of particles were sorted manually to create a learning set \[note the total size later\] which then was used to train and predict classifications for the other vignettes. Ultimately, all particles with ABD \[check for later\] greater than 20 microns were manually validated by a single expert and that is the data used here. \[will need to reference ID guides\]

In imaging, VisualSpreadsheet reports several metrics related to size including length and width, which were used to calculate biovolume of each individual. The biovolume of each individual can then be multiplied to get a biomass (in carbon). The total biomass of any group of plankton per unit volume can then be calculated:

\begin{align}
mgCm^{-3} = \frac{mgC}{v}
\end{align}

In plankton ecology/biological oceanography this is what researchers are typically trying to report. Estimates of $mgCm^{-3}$ are either done with microscopy or imaging but in either case, it involves converting counts to biovolume to biomass. Because the counts of individuals tend to have large amounts of zeros.

There are several ways to approach this:

# Approach 1: Log-normal regression

An initial approach may be to simply model the data using a log-normal distribution. This is typically the primary approach taken:

### Basic Case:

Terms:

-   $y$ - biomass concentration (calculated from data of biovolume / measured volume)

-   $i$ - the number of observations

-   $\sigma$ - sampling error / noise

\begin{align}
    \text{Data Model:}\\
    log(y_i) &\sim N(\mu_i, \sigma^2)\\
    \\
    \text{Parameter Model:}\\
    \mu_i &= X'\beta
\end{align}

text:
\begin{align}
    y_{g,i} &\sim LN(\mu_{g,i}, s^2)\\
    \\
    \mu_{g,i} &= \pmb{\beta_g X_i}\\
    \\
    \pmb{\beta_g} &\sim N(\pmb{\theta_g}, \sigma^2_g)\\
    \pmb{\theta_g} &\sim N(0, \pmb{\tau^2})\\
    \pmb{\tau} &\sim [\pmb{\tau}]
\end{align}

$$

# Approach 1: Hurdle Model

The 0's are an issue given that there are many instances of non-observation where biomass is zero (e.g. $y_{g,i} = 0$) For this a hurdle model may be appropriate as we can separately model the occurance probability and Such as:

$$
\begin{align}
    y_{i} \sim \ &\left\{ 
        \begin{array}{l}
            0; z_i = 0\\
            d_i; z_i = 1
        \end{array} \right.
\end{align}
$$

Now there's two models which contribute to the observed biomass $y_i$. First, we can model whether or not a given plankter is present based on $z_i$

```{latex}

\begin{align}
    &\text{Occurance Model:}\\
    z_i &\sim Bern(\pi_i) \\ 
    logit(\pmb{\pi}) &= \pmb{X}'\pmb{\alpha}\\
    
    \pmb{\alpha} &\sim [\pmb{\alpha}]
\end{align}

```

Here, $\pmb{\alpha}$ denotes the coefficient matrix for the effect of different environmental covariates.

Then separately, we can model the expected biomass concentration, given that some plankton are observed ($z_i = 1$)

\$\$ \begin{align}
    &\text{Biomass Model:}\\
    d_i &\sim LN(\mu_i, \sigma^2) \\ 
    \mu_i &= \pmb{X}'\pmb{\beta}\\
    
    \pmb{\beta} &\sim [\pmb{\beta}]
\end{align} \$\$

Here, I've written a general, non-hierarchical case. This approach was done in detail by Mutshinda et al. 2022, where they modelled the probability of $Y_{s,t}$ for different species, $s$ at times $t$. I've rewritten their approach to be consistent with the notation I described above: $$
\begin{align}
    [y_{s,t}] = \left\{ 
        \begin{array}{l}
            (1 - \pi_{s,t})\\
            \pi_{s,t} \cdot LN(\mu_{s,t}, \sigma^2_s) 
        \end{array} \right.
\end{align}
$$

In this approach, the biomass concentraiton is essentially modeled separately for each $s$ species, which has it's own occurance probability, $\pi_s$ and expected biomass concentration, $\mu_s$. Yet conceivably, it is more appropriate to model similar taxonomic groups in a hierarchical structure with a group-level mean effect and species/genus level variation, as I described in approach 0.

# Approach 2: Mixed Model

The problem with both approaches described above is that it doesn't really reflect the true system. Really, plankton occur in the water as counts - whole individuals. Then the biomass concentration is determined both by the number of individuals and the size of those individuals:

$$
y_i = n_i \cdot b_i
$$

Observations of the total biomass concentration $\y_i$ can be modeled separately as factors contributing to abundance, $n$ and factors contributing to the biomass of individuals $b$.

If we acknowledge that our estimates of $y_{g,i}$ described previously are really a derived estimate of counts, $n$, and a count to biomass conversion. In many cases, this is a fixed value from some published study which is then multiplied by the observed counts. However, with the employment of imaging analyses to process our phytoplankton samples, we actually are gathering real data on at least the biovolume of each individual.

So we can really describe $y_{g,t} = n_{g,t} \times b_{g,i} \times c_g$ where $n_{g,t}$ are the counts of the $g$ group of phytoplankton at time $t$. The biomass of group $g$ is defined as $b_{g,i}$ where $i$ is a subset of $t$ where $n_{g,t}$ \> 0 and $c_g$ is a constant from literature values.

This approach may offer several advantages. First, by treating our occurrances as counts, it is possible to include 0s with the observations, rather than having to develop separate model. This is particularly useful in the case of variable sampling volume inherent to imaging studies (or a common net-tow) where the number of individuals counted may vary based on the sampling effort.

Second, we can also explicitly model the variation around individual sizes in our second model. By doing this, we can expand the model to include effects which may influence the size of individual cells. Now we can ask how both the number and the size of different phytoplankton are influenced by environmental factors - which have different ecological implications.

This approach logically matches the system more clearly. Really, the presence of observing a plankton should follow some count distribution. Then the size/biomass of individuals are more likely to follow a normal distribution.

In the first approach we have a lot of derived quantities then try to model the data but are forced to do weird things like a log-normal distribution.