---
title: Basic Description of Models
format:
    pdf:
        toc: false
---

# Background

Data are collected from FlowCam images of microplankton from the Mission-Aransas Estuary. Samples range from 2014 to 2021 collected roughly every month at four stations. Images were initially segemented using VisualSpreadsheet (version ranged from 2.0 to 4.0) which provided collages of individual vignettes of particles. Single image files were then extracted using MorphoCut \[will need to cite and link code\], which formats images to be individually processed in EcoTaxa. The vignettes of particles were sorted manually to create a learning set \[note the total size later\] which then was used to train and predict classifications for the other vignettes. Ultimately, all particles with ABD \[check for later\] greater than 20 microns were manually validated by a single expert and that is the data used here. \[will need to reference ID guides\]

In imaging, VisualSpreadsheet reports several metrics related to size including length and width, which were used to calculate biovolume of each individual. The biovolume of each individual can then be multiplied to get a biomass (in carbon). The total biomass of any group of plankton per unit volume can then be calculated:

\begin{align}
mgCm^{-3} = \frac{mgC}{v}
\end{align}

In plankton ecology/biological oceanography this is what researchers typically report. Estimates of $mgCm^{-3}$ are either done with microscopy or imaging but in either case, it involves converting counts to biovolume to biomass. Because the counts of individuals tend to have excess zeros.

There are several ways to approach this:

# Approach 1: Log-normal regression

An initial approach may be to simply model the data using a log-normal distribution. This is typically the primary approach taken:

### Basic Case:

Terms:

-   $y$ - biomass concentration (calculated from data of biovolume / measured volume)

-   $i$ - the observation index

-   $\sigma^2$ - sampling variance

-   $j$ - the predictor index

\begin{align}
    \text{log}(y_i) &\sim \text{N}(\mu_i, \sigma^2)\\
    \mu_i &= \pmb{x}_i'\pmb{\beta}\\
    \pmb{\beta} &\sim [\pmb{\beta}]\\
    \sigma^2 &\sim [\sigma^2] 
\end{align}

Using this, the posterior is $[\pmb{\beta}| y]$. Then over a range of possible values for a $j^{\text{th}}$ predictor, the expected value and high density interval can be estimated for $\mu$ with $\text{E}(\pmb{\text{X}, \beta} | \pmb{y})$. That is what I've plotted in the slides. 

### Hierarchical Case:

-   $y$ - biomass concentration (calculated from data of biovolume / measured volume)

-   $i$ - the observation index

-   $\sigma^2$ - sampling variance

-   $j$ - the predictor index

-   $g$ - the group index

-   $\pmb{\beta}_g$ - group-level effects

-   $\pmb{\theta}$ - global mean effects

-   $\tau^2$ - group effect variance


\begin{align}
    \text{log}(y_{g,i}) &\sim \text{N}(\mu_{g,i}, \sigma^2)\\
    \mu_{g,i} &= \pmb{x}_i'\pmb{\beta}_g\\
    \pmb{\beta}_g &\sim \text{N}(\pmb{\theta},\pmb{\tau}^2)\\
    \pmb{\theta} &\sim [\pmb{\theta}]\\
    \pmb{\tau}^2 &\sim [\pmb{\tau}^2]\\
    \sigma^2 &\sim [\sigma^2] 
\end{align}


With posterior $[\pmb{\beta}_g | y]$, I plotted the individual expected value for a group. But I also looked in some cases at the global-mean expected value using the posterior across a range of predictors.

In all cases, if I'm interested in the expected value across a range of salinity, I used the posterior distributions for the slope parameters, multiplied by a range of salinity values with all other predictors held at the mean value.

# QUESTIONS:

For analyzing the total biomass concentration (across all g groups), I've done it two ways: 

1. Just in a non-hierarchical sense described above, I'm describing total expected biomass concentration $\text{E}(\textbf{X}'\pmb{\beta} | \pmb{y})$

2. If I do a hierarchical model with group-level effects, can I describe the total biomass change as a sum of the expected group level biomass? $\sum_g \text{E}(\textbf{X}'\pmb{\beta}_g | \pmb{y})$

# Approach 2: Hurdle Model

This [paper](https://link.springer.com/article/10.1007/s10750-021-04789-2) describes in more detail but here I use different terms to try and be consistent acrosss models. Also they don't do a hierarhcical (multi-level) model, they just fit separate intercepts and slopes for all individual groups if I'm not mistaken.

Terms: 

- $y$ - observed biomass concentration 

- $z$ - indicator of presence/absence 

- $b$ - biomass concentration 

- $\psi$ - occurrence probability 

- $\pmb{\alpha}$ - predictors for occurrence model 

- $\pmb{\beta}$ - predictors for the biomass model 

- $\sigma^2$ - observation variance

First the data model for the mixture is described as:

\begin{align}
    y_{i} \sim \ &\left\{ 
        \begin{array}{l}
            0; z_i = 0\\ 
            b_i; z_i = 1
        \end{array} \right.
\end{align}


This is broken into the occurrence and biomass models separately:


\begin{align}
    z_i &\sim \text{Bern}(\psi_i) \\ 
    \text{logit}(\psi) &= \pmb{x}_i'\pmb{\alpha}\\
    \pmb{\alpha} &\sim [\pmb{\alpha}]
\end{align}


Then separately, we can model the biomass concentration, given that some plankton are observed ($z_i = 1$)

\begin{align}
    \text{log}(b_i) &\sim \text{N}(\mu_i, \sigma^2) \\ 
    \mu_i &= \pmb{x}_i'\pmb{\beta}\\
    \pmb{\beta} &\sim [\pmb{\beta}]\\
    \sigma^2 &\sim [\sigma^2]
\end{align}


I've only written this one as a non-hierarhical case, but I also can add levels to make group-specific predictors for betas and alphas. To calculate the expected value for biomass concentration, I can use the posterior distributions for $[\pmb{\alpha}, \pmb{\beta} | \pmb{y}]$.

All together: $y = (1-\psi)* 0 + \psi * \text{exp}(\textbf{X}'\pmb{\beta})$

So I calculated this using $[\psi |y] * \text{exp}(\textbf{X}'[\pmb{\beta}|y])$

\*\* Modification attempt: \*\*

$\text{E}(\psi | \pmb{y}) * {\text{exp(E}(}\textbf{X}'\pmb{\beta}|\pmb{y}))$

# Approach 3: Two-part Model

In both cases above, I first calculate the biomass concentration then construct the model, fitted to that data. However, what I'm doing is separately modelling the counts ($n_i$) and the individual biomass $d_i$

\begin{align}
y_i = \frac{\Sigma_i n_i*d_i}{v_i}
\end{align}


### Basic Case:

Terms:

-   $y$ - biomass concentration

-   $n$ - observed counts 

-   $d$ - individual cell biomass 

-   $\lambda = \frac{c}{v}$ - rate parameter or concentration; counts (c) divided by imaging volume (v) 

-   $\pmb{\beta}$ - parameters for the count regression effects 

-   $\pmb{\alpha}$ - parameters for individual biomass effects 

-   $v$ - imaging volume

-   $\eta$ - mean of the log for individual cell biomass

-   $\sigma^2$ - individual cell variance


First modeling the counts can be done with a count-distribution regression, here I've used Poisson:


\begin{align}
    n_i &\sim \text{Pois}(\lambda_i)\\
    \text{log}(\lambda_i) &= \text{log}(c_i /v_i)\\
    \text{log}(c_i) &= \textbf{x}_i'\pmb{\beta} + \text{log}(v_i)\\
    \pmb{\beta} &\sim [\pmb{\beta}]
\end{align}


Then the individual biomass of each cell is modelled as:


\begin{align}
    \text{log}(d_i) &\sim \text{N}(\eta_i, \sigma^2)\\
    \eta_i &= \textbf{x}_i'\pmb{\alpha}\\
    \pmb{\alpha} &\sim [\pmb{\alpha}]\\
    \sigma^2 &\sim [\sigma^2]
\end{align}


From this, I am estimating the posterior distribution for the regression parameters $[\pmb{\beta, \alpha} | \pmb{y}]$ which I use to estimate $\text{E}(\textbf{X}'\pmb{\beta} | \pmb{y})$ and $\text{E}({\textbf{X}'\pmb{\alpha}}|\pmb{y})$

From this, I calculate a derived value to represent an expected biomass concentration.

### Hierarchical Case:

Terms (in addition to basic case):

-   $g$ - the group index

-   $\omega$ - global-mean effect for count

-   $\pmb{\Sigma}^2$ - variance of count effects

-   $\gamma$ - global-mean effect for biomass

-   $\pmb{T}^2$ - variance of biomass effects

Count model:


\begin{align}
    n_{g,i} &\sim \text{Pois}(\lambda_{g.i})\\
    \text{log}(\lambda_{g,i}) &= \text{log}(c_{g,i}/v_i)\\
    \text{log}(c_{g,i}) &= \textbf{x}_i'{\pmb{\beta}_g} + log(v_i)\\
    \pmb{\beta}_g &\sim \text{N}(\pmb{\omega}, \pmb{\Sigma}^2)\\
    \pmb{\omega} &\sim [\pmb{\omega}]\\
    \pmb{\Sigma}^2 &\sim [\pmb{\Sigma}^2]\\
\end{align}



Biomass model:

\begin{align}
   \text{log}(d_{g,i}) &\sim \text{N}(\eta_{g,i}, \sigma^2)\\
    \eta_{g,i} &= \textbf{x}_i'\pmb{\alpha}_g\\
    \pmb{\alpha}_g &\sim \text{N}(\pmb{\gamma}, \pmb{T}^2)\\
    \pmb{\gamma} &\sim [\pmb{\gamma}]\\
    \pmb{T}^2 &\sim [\pmb{T}^2]\\
    \pmb{\sigma}^2 &\sim [\pmb{\sigma}^2]
\end{align}


Then from these posteriors, I can calculate the expected values for group-level $\lambda$ and $d$.